require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MusicsController, type: :controller do
  let(:admin_user) { User.all.first }
  before(:each) { sign_in admin_user }

  # This should return the minimal set of attributes required to create a valid
  # Music. As you add validations to Music, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { title: '恋', author: '星野源', published_on: Time.zone.now, showing: true, price: 1200, play_time: 300}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MusicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all musics as @musics" do
      music = Music.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:musics).count).to eq(4)
    end
  end

  describe "GET #show" do
    it "assigns the requested music as @music" do
      music = Music.create! valid_attributes
      get :show, params: {id: music.to_param}, session: valid_session
      expect(assigns(:music)).to eq(music)
    end
  end

  describe "GET #new" do
    it "assigns a new music as @music" do
      get :new, params: {}, session: valid_session
      expect(assigns(:music)).to be_a_new(Music)
    end
  end

  describe "GET #edit" do
    it "assigns the requested music as @music" do
      music = Music.create! valid_attributes
      get :edit, params: {id: music.to_param}, session: valid_session
      expect(assigns(:music)).to eq(music)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Music" do
        expect {
          post :create, params: {music: valid_attributes}, session: valid_session
        }.to change(Music, :count).by(1)
      end

      it "assigns a newly created music as @music" do
        post :create, params: {music: valid_attributes}, session: valid_session
        expect(assigns(:music)).to be_a(Music)
        expect(assigns(:music)).to be_persisted
      end

      it "redirects to the created music" do
        post :create, params: {music: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Music.last)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { title: '大きなのっぽの古時計'}
      }

      it "updates the requested music" do
        music = Music.create! valid_attributes
        put :update, params: {id: music.to_param, music: new_attributes}, session: valid_session
        music.reload
        expect(music.title).to eq new_attributes[:title]
      end

      it "assigns the requested music as @music" do
        music = Music.create! valid_attributes
        put :update, params: {id: music.to_param, music: valid_attributes}, session: valid_session
        expect(assigns(:music)).to eq(music)
      end

      it "redirects to the music" do
        music = Music.create! valid_attributes
        put :update, params: {id: music.to_param, music: valid_attributes}, session: valid_session
        expect(response).to redirect_to(music)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested music" do
      music = Music.create! valid_attributes
      expect {
        delete :destroy, params: {id: music.to_param}, session: valid_session
      }.to change(Music, :count).by(-1)
    end

    it "redirects to the musics list" do
      music = Music.create! valid_attributes
      delete :destroy, params: {id: music.to_param}, session: valid_session
      expect(response).to redirect_to(musics_url)
    end
  end

end
